# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Kwiki-Notify-Mail
version:      0.04
version_from: lib/Kwiki/Notify/Mail.pm
installdirs:  site
requires:
    Kwiki:                         0.37
    MIME::Lite:                    0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
